openapi: 3.0.1
info:
  title: Проектные данные
  version: v0
paths:
  /api/ktMain/project:
    get:
      tags:
        - Основное
      operationId: getProject
      responses:
        "200":
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ProjectPaginatedResponse'
    post:
      tags:
        - Основное
      operationId: postProject
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProjectResponse'
  /api/ktMain/project/{projectUid}:
    post:
      tags:
        - Основное
      operationId: postProjectUid
      parameters:
        - name: projectUid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProjectResponse'

components:
  schemas:

    Project:
      type: object
      description: Проект
      properties:
        name:
          type: string
          description: Наименование
          example: Строительство Верхнечусовских Городков
        code:
          type: string
          description: Шифр
          example: СВГ-2023/1
        country:
          type: string
          description: Страна
          example: Россия
        region:
          type: string
          description: Область / Край
          example: Пермский край
        city:
          type: string
          description: Населённый пункт
          example: Чусовой
        street:
          type: string
          description: Улица / проспект
          example: Ленина
        house:
          type: string
          description: Дом
          example: 1
        building:
          type: string
          description: Корпус
          example: А
        postCode:
          type: string
          description: Почтовый индекс
          example: 614000
        objectStatus:
          $ref: '#/components/schemas/ObjectStatus'
        uid:
          type: string
          description: Уникальный идентификатор. При создании отсутствует
          example: 3d9e8e24-2a66-41b7-ab4d-c2a1f8374d3b

    ObjectStatus:
      type: object
      description: Статус объекта
      properties:
        changeDate:
          type: string
          description: Дата создания или изменения. При запросе на создание отсутствует
          example: 2023-05-26T07:30:25
        statusId:
          type: integer
          description: Статус объекта
          example: 1

    PaginatedResponse:
      type: object
      description: Базовый постраничный ответ
      properties:
        total:
          type: integer
          description: Общее количество объектов в БД
          example: 1

    ProjectPaginatedResponse:
      allOf:
        - $ref: '#/components/schemas/PaginatedResponse'
        - type: object
          properties:
            result:
              type: array
              items:
                $ref: '#/components/schemas/Project'

    ProjectResponse:
      type: object
      properties:
        result:
          $ref: '#/components/schemas/ProjectResult'

    ProjectResult:
      type: object
      properties:
        result:
          $ref: '#/components/schemas/Project'